var stemList_6 = [
	[0, 'germ', 'vital or related', 
		' *germane  *germinate  *germicide  *germinal  *germ'],
	[0, 'greg', 'group', 
		' *gregarious  *egregious  *gregariously  *segregate  *congregate  *aggregate'],
	[0, 'mar', 'sea', 
		' *marine  *marina  *ultramarine  *martime  *mariner  *marinate  *submarine'],
	[0, 'prim', 'first', 
		' *prime  *primary  *primate  *primogeniture  *primeval  *prima  *donna  *primo'],
	[0, 'pyro', 'fire', 
		' *pyre  *pyromania  *pyrotechnic  *pyrogenic  *pyrophobia  *pyrometer'],
	[0, 'clam', 'cry out', 
		' *clamorous  *exclamation  *clamor  *exclamatory  *clamant  *declaim'],
	[0, 'plu', 'more',
		' *plural  *plurality  *plus  *pluralize  *pluriaxial  *pluralism  *nonplussed'],
	[0, 'tang', 'touch',
		'  *tangible  *tangent  *tangle  *tangential  *cotangent  *intangible'],
	[0, 'string', 'bind',
		'  *stringent  *string  *stringy  *astringent  *stringer'],
	[0, 'liber','free',
		'  *liberate  *liberty  *liberal  *libertine  *deliberate  *libertarian'],
	[0, 'junct','join',
		'  *junction  *conjunction  *juncture  *disjunct  *injunction  *adjunct'],
	[0, 'clud', 'close',
		'  *exclude  *include  *preclude  *exclusive  *occlude  *conclude  *cloister'],
	[0, 'se', 'apart',
		'  *secede  *secret  *sedition  *seduce  *segregate  *select  *sedulous  *seperate'],
	[0, 'trib', 'pay',
		'  *tribute  *tributary  *retribution  *contribution  *attribute  *diatribe  *distribute'],
	[0, 'dign', 'worthy',
		'  *dignify  *dignity  *condign  *dignitary  *undignified  *indignation'],
	[0, 'luc', 'light',
		'  *lucid  *translucent  *lucidity  *Lucifer  *elucidate  *lucent  *lucubrate'],
	[0, 'rupt', 'break',
		'  *erupt  *disrupt  *rupture  *corrupt  *abrupt  *uncorruptible'],
	[0, 'grat', 'pleasing',
		'  *gratifying  *gratitude  *ingrate  *grateful  *gratuitous  *ingratitate'],
	[0, 'medi', 'middle',
		'  *median  *meditate  *medium  *mediocre  *mediterranean *in medias res'],
	[0, 'soph', 'wisdom',
		'  *sophomore  *sophisticated  *sophist  *philosophy  *pansophy  *theosophy'],
	[0, 'curr', 'run',
		'  *current  *undercurrent  *currently  *recurrent  *currency  *incur'],
	[0, 'tempor', 'time',
		'  *temporal  *contemporary  *temporize  *temporarily  *tempus fugit'],
	[0, 'migr', 'wander',
		'  *migrate  *transmigration  *migrant  *migratory  *emigrant  *immigrant'],
	[0, 'trans', 'across',
		'  *transfer  *translate  *transmit  *transfusion  *translucent  *transcend'],
	[0, 'gamy', 'marriage',
		'  *monogamy  *polygamy  *bigamy  *gamete  *autogamous  *exogamy']		
]