//note: remember to add var name of new stem list into the variable allStemList in the bottom

/* use array to store all the stem lists in this js file
*/
var stemList_1 = [
		['ante', 'before', ' *antedate  antecedent  antebellum  anterior  ante meridian  antepenult'],
		['anti', 'against', ' *anti-aircraft  antibody  anticlimax  anticline  antitoxin  antithesis'],
		['bi', 'two', ' *bilateral  bicycle  bimonth  biped  bipolar  binocular  bicuspid'],
		['circum', 'around', ' *circumnavigate  circumspect  circumvent  circumlocution  circus'],
		['com', 'together', ' *combination  comfort  commensurate  common  complete  combo'],
		['con', 'together', ' *contract  confidence  confine  confederate  conjunction  contact'],
		['de', 'down', ' *deposit  descent  despicable  denounce  deduct  demolish  decreipt  deplete'],
		['dis', 'away', ' *distract  distort  dispute  dissonant  disperse  dismiss  dissuade  disprove'],
		['equi', 'equal', ' *equitable  equilateral  equivocate  equinox  equation  equilibrium'],
		['extra', 'beyond', ' *extraterrestrial  extraordinary  extravagant  extrovert  extramural'],
		['inter', 'between', ' *international  interdepartmental  interstellar  interject  interlude'],
		['intra', 'within', ' *intracellular  intravenous  intracranial  intrastate  intrauterine'],
		['intro', 'into', ' *introduce  introspective  introvert  introject  introrse  intromission'],
		['mal', 'bad', ' *malevolent  malcontent  malicious  malign  malady  malapropism  malonym'],
		['mis', 'bad', ' *misfit  mistake  misfortune  misfire  misery  miser  misdeed  misguided'],
		['non', 'not', ' *nonstop  nonprofit  none  noncomforty  nonplussed  nonchalant'],
		['post', 'after', ' *postgraduate  posthumous   postscript  posterity  posterior  postlude'],
		['pre', 'before', ' *prelude  preposition  premonitionp remature  predict  predecessor'],
		['semi', 'half', ' *semitone  semiaquatic  semicircle  semiweekly  semiannual  semiformal'],
		['sub', 'under', ' *subterranean  subtract  subordinate submarine  subterfudge  substanial'],
		['super', 'over', ' *supervise  superb  superior  superfluos  supercilious  supernatural'],
		['syn', 'together', ' *synthetic  synchronize  syndrome  synonym  synopsis syntax'],
		['sym', 'together', ' *sympathy  symbiosis  symbol  symmetry  symphony  symposium'],
		['tri', 'three', ' *tricycle  triangle  triceps  triad  trichotomy  triceratops  trivia  trialogue'],
		['un', 'not', ' *unfit  unequal  undone  unequivocal  unearned  unconventional  untenable']
];

var stemList_2 = [
		['archy', 'government', ' *monarchy  oligarchy  hierarchy  anarchy  matriarchal  patriarchy'],
		['ard', 'always', ' *drunkard  coward  braggart  laggard  dullard  sluggard  nigerardy'],
		['cide', 'kill', ' *herbicide  homicide  matricide  suicide  regicide  genocide  fratricide'],
		['ician', 'specialist', ' *technician  musician  beautician  physician  statistician  clinician'],
		['itis', 'infection', ' *appendicitis  tonsillitis  bursitis  arthritis  gastroenteritis  colitis'],
		['aqua', 'water', ' *aquarium  aquatic  aquaplane  aqueduct  aquifer  aqueous  semiaquatic'],
		['audi', 'hear', ' *audiophile  audience  audition  auditory  audiometer  audit  audiology'],
		['bell', 'war', ' *bellicose  belligerent  bellow  rebel  casus belli  counterrebellion'],
		['cap', 'take', ' *capture  captive  captor  captious  captivate  captivity  caption  capsule'],
		['cise', 'cut', ' *excise  incisors  incision  circumcise  incisive  precise  concise  decision'],
		['bio', 'life', ' *biography  biology  biomorphic  biochemistry  exobiology  biogenesis'],
		['auto', 'self', ' *autobiography  automobile  autograph  automatic  automaton  autocracy'],
		['port', 'carry', ' *transport  import  report  porter  deport  important  portage  portly'],
		['scrib', 'write', ' *scribble  inscribe  scribe  describe  conscription  transcribe  ascribe'],
		['logy', 'science', ' *biology  anthropology  geology  entomology  philology  mythology'],
		['dict', 'say', ' *dictionary  predict  malediction  dictation  addict  interdict  contradict'],
		['cred', 'believe', ' *credit  incredible  credible  incredulous  discredited  credibility  credo'],
		['cent', 'one hundred', ' *century  bicentennial  centimeter  centipede  centurion  cent'],
		['neo', 'new', ' *neologism  neophyte  neon  neolithic  neoclassic  neoPlatonist  neonatal'],
		['ad', 'to', ' *adhesive  adapt  addendum  addition  adherent  addict  advent  advocate'],
		['cede', 'go', ' *recede  precede  antecedent  proceed  secede  concede  intercede  succeed'],
		['miss', 'send', ' *dismiss  remiss  missile  admission  missionary  emission  promissory'],
		['centri', 'center', ' *centrifugal  centripetal  centrist  concentric  decentralize  eccentric'],
		['biblio', 'book', ' *bibliography  bibliophile  bibliolatry  bible  bibliomania  bibliophobia'],
		['anthropo', 'man', ' *anthropology  anthropomorphic  anthropoid  lycanthrope']
];

var stemList_3 = [
		['homo', 'same', ' *homogenize  homonym  homophone  homologuos  homozygous'],
		['spec', 'look', ' *spectacles  specter  speck  specious  spectrum  respect  inspect  prospectus'],
		['duct', 'lead', ' *conduct  ductile  induct  product  reduction  deduction  reproduction'],
		['fer', 'carry', ' *transfer  infer  refer  defer  ferry   conifer  Lucifer  aquifer  auriferous'],
		['pend', 'hang', ' *pending  pendulum  pendant  impending  depend  penduluos  suspend'],
		['micro', 'small', ' * micron  microscope  microwave   microphone  microcosm  microbiotic'],
		['hydro', 'water', ' *hydroplane  hydroponics  dehydrate  hydrant  hydrogen  hydrophobia'],
		['photo', 'light', ' *photograph  photometer  photon  photogenic  photosynthesis'],
		['pan', 'all', ' *panorama  panoply  pandemic  pantheism  pantheon  panamerican'],
		['penta', 'five', ' *pentagram  pentagon  pentameter  pentatholon  pentarchy  penthedron'],
		['tele', 'far', ' *telescope  telephone  telekinesis  telepathy  teleology  telesthesia  telex'],
		['vid', 'look', ' *video  invidous  Montevideo  evidence  provide  videogenic  vide  vidlicet'],
		['omni', 'all', ' * omnifarious  omnipotent  omnivorous  omniscient  omnibus  omnipresent'],
		['ex', 'out', ' * exit  except  excise  exculpate  exludicate  exorbitant  eccentric  enumerate'],
		['poly', 'many', ' *polyphony  polygyny  polygamy  allopolyploidy  polyvalent  polychrome'],
		['re', 'again', ' *return  review  retouch  reiterate  retail  revive  regenerate  regurgitate'],
		['hypo', 'under', ' *hypodermic  hypocrite  hypotenuse  hypothermia  hypothesis'],
		['pseudo', 'false', ' *pseudonym  pseudopod  pseudomorphic  pseudoscience  pseudoevent'],
		['neuro', 'nerve', ' *neuron  neurosurgeon  neurosis  neurology  neuralgia  neurotomy'],
		['tomy', 'cut', ' *tonsillectomy  appendectomy  neurotomy  dichotomy  anatomy  lobotomy'],
		['hema', 'blood', ' *hematic  hematite  hematology  hematoma  hemal  hematogenesis'],
		['proto', 'first', ' *protoplasm  prototype  Protozoa  proton  protohuman  protomorphic'],
		['phon', 'sound', ' *symphony  telephone  phonetic  phonograph euphony cacophony'],
		['mono', 'one', ' *monotonous  monomania  monocular  monogamous  monolithic  monotone'],
		['viv', 'life', ' *vivid  vivisection  vivacious  convivial  [bon vivant]  viva  viviparous revive']
	];

var stemList_4 = [
		['morph', 'shape', ' *amorphous  morphology  polymorphously  mesomorph  protomorphic'],
		['vest', 'clothes', ' *vestry  vestment  vestibule  vest  investiture  devest  divestiture'],
		['bene', 'good', ' *benefit  benevolent  beneficial  benediction  benefactor  benign'],
		['pond', 'weight', ' *ponderoud  ponder  preponderant  pound  imponderable  compound'],
		['corp', 'body', ' *corpulent  corporation  corporeal  corporal  corpse  corpuscle'],
		['dorm', 'sleep', ' *dormitory  dormant  dormer  dormancy  dormitive  dormient'],
		['pater', 'father', ' *paternalistic  patronize  paternity  patriarch  expatriate  paterfamilias'],
		['nov', 'new', ' *novel  nova  novice  novitiate  Nova Scotia  innovation  rennovate'],
		['punct', 'point', ' *punctuate  punctilious  puncture  punctual  acupuncture  contrapunctal'],
		['ject', 'throw', ' *eject  reject  conjecture  dejected  inject  subject  projection  interject'],
		['tion', 'act or state', ' *completion  reaction  devastation  production  creation  transition'],
		['loco', 'place', ' *locomotive  location  local  locus  relocate  dislocate  localize  locomotor'],
		['dox', 'opinion', ' *orthodox  heterodox  doxology  indoctrinate paradox'],
		['amphi', 'both', ' *amphibious  amphitheater  amphibian  amphigory  amphibolous'],
		['magn', 'great', ' *Magn Carta  magnanimous  magnate  magnificent  magnum opus'],
		['eu', 'good', ' *Eucharist  euphony  eulogy  euphemism  Europe  eugenics  euglena'],
		['endo', 'within', ' *endoplasm  endocrine  endogamous  endoskeleton  endothermic'],
		['phobia', 'fear', ' *clausphobia  acrophobia  xenophobia  agoraphobia hydrphobia'],
		['ortho', 'straight', ' *orthopedics  orthodontist  orthodox  orthography  orthogonal'],
		['put', 'think', ' *reputation  putative  impute  dispute  computer  disreputable'],
		['ver', 'true', ' *verify  veracity  veritable  verdict  versimiliude  aver  cinema  verite'],
		['matri', 'mother', ' *matricide  matron  matriarch  matrimony  metropolis  matrilineal'],
		['mega', 'large', ' *megalith  megaphone  megalomania  megalopolis  megahertz'],
		['pop', 'people', ' *popular  populist  populate  population  popularize  populous'],
		['sangui', 'blood', ' *sanguinary  sanguine  consanguinity  sangfroid  sangria']
];

var stemList_5 = [
		['vita', 'life', ' *vitamin  *vitality  *vital  *revitalize  *viable  *vitalism  *devitalize'],
		['demo', 'people', ' *democracy  demography  undemocratic  democratize'],
		['stereo', 'solid', ' *stereoscope  stereophonic  stereotype  stereopticon  stereotropism'],
		['ism', 'doctrine', ' *Marxism  capitalism  Imaginism  Cubism nihilism  pluralism  tribalism'],
		['cogn', 'know', ' *recognize  cognizant  incognito  cognoscenti  cognomen  precognition'],
		['sur', 'over', ' *surplus  surpass  surcharge  surface  surfeit  surmount  surname  surtax'],
		['alter', 'other', ' *alternator  alteration  alter ego   alternative  altruism  altercation'],
		['astr', 'star', ' *astronomy  astrology  asteroid  disaster  asterdisk  astrophysics  astrolabe'],
		['dyna', 'power', ' *dynamic  dynamo  dynamite  dynasty  dynamometer  dinosaur'],
		['chron', 'time', ' *chronometer  chronological  synchronize  chronic  anachronism'],
		['hyper', 'over', ' *hyperactive  hyperventilate  hyperbole  hyperacidity  hypertension'],
		['luna', 'moon', ' *lunar  lunatic  lunate  luna moth  lunnete  sublunar lunular'],
		['octa', 'eight', ' *octameter  octageneration  octagon  octarchy  octave  octopus octahedron'],
		['gyro', 'turn', ' *gyration  gyroscope  gyre  gyrate  spirogyra  gyromagnetic  gyrocompass'],
		['contra', 'against', ' *contradict  contrary  contrast  contrapuntal  contraband  contravene'],
		['geo', 'earth', ' *geography  geothermal  geology  geophisycs  geometry  geosynchronous'],
		['helio', 'sun', ' *helios  heliotropic  heliocentric  heliograph  perihelion  aphelion'],
		['thermo', 'heat', ' *thermostat  thermos  thermotropic  thermonuclear  thermocouple'],
		['tetra', 'four', ' *tetrameter tetrahedron  tetroxide  tetragon  tetrachloride  tetracycline'],
		['meter', 'measure', ' *thermometer  millimeter  octameter  hydrometer  odometer'],
		['scope', 'look', ' *telescope  microscope  periscope  radarscope  horoscope  electroscope'],
		['son', 'sound', ' *sonar  unision  sonorous  song  sonnet  dissonance n resonant  supersonic'],
		['dec', 'ten', ' *decade  decaliter  decimal  decagon  decathlon  decimate  duodecahedron'],
		['stell', 'star', ' *interstellar  stelliform  stellar  constellation  stellate  stellify'],
		['amat', 'love', ' *amatory  amateur  amoros  amiable  amigo  amour-propre  amity']
];

var stemList_6 = [
		['germ', 'vital or related', ' *germane  *germinate  *germicide  *germinal  *germ'],
		['greg', 'group', ' *gregarious  *egregious  *gregariously  *segregate  *congregate  *aggregate'],
		['mar', 'sea', ' *marine  *marina  *ultramarine  *martime  *mariner  *marinate  *submarine'],
		['prim', 'first', ' *prime  *primary  *primate  *primogeniture  *primeval  *prima  *donna  *primo'],
		['pyro', 'fire', ' *pyre  *pyromania  *pyrotechnic  *pyrogenic  *pyrophobia  *pyrometer'],
		['clam', 'cry out', ' *clamorous  *exclamation  *clamor  *exclamatory  *clamant  *declaim'],
		['plu', 'more', ' *plural  *plurality  *plus  *pluralize  *pluriaxial  *pluralism  *nonplussed'],
		['tang', 'touch', ' *tangible  *tangent  *tangle  *tangential  *cotangent  *intangible'],
		['string', 'bind', ' *stringent  *string  *stringy  *astringent  *stringer'],
		['liber','free', ' *liberate  *liberty  *liberal  *libertine  *deliberate  *libertarian'],
		['junct','join', ' *junction  *conjunction  *juncture  *disjunct  *injunction  *adjunct'],
		['clud', 'close', ' *exclude  *include  *preclude  *exclusive  *occlude  *conclude  *cloister'],
		['se', 'apart', ' *secede  *secret  *sedition  *seduce  *segregate  *select  *sedulous  *seperate'],
		['trib', 'pay', ' *tribute  *tributary  *retribution  *contribution  *attribute  *diatribe  *distribute'],
		['dign', 'worthy', ' *dignify  *dignity  *condign  *dignitary  *undignified  *indignation'],
		['luc', 'light', ' *lucid  *translucent  *lucidity  *Lucifer  *elucidate  *lucent  *lucubrate'],
		['rupt', 'break', ' *erupt  *disrupt  *rupture  *corrupt  *abrupt  *uncorruptible'],
		['grat', 'pleasing', ' *gratifying  *gratitude  *ingrate  *grateful  *gratuitous  *ingratitate'],
		['medi', 'middle', ' *median  *meditate  *medium  *mediocre  *mediterranean *in medias res'],
		['soph', 'wisdom', ' *sophomore  *sophisticated  *sophist  *philosophy  *pansophy  *theosophy'],
		['curr', 'run', ' *current  *undercurrent  *currently  *recurrent  *currency  *incur'],
		['tempor', 'time', ' *temporal  *contemporary  *temporize  *temporarily  *tempus fugit'],
		['migr', 'wander', ' *migrate  *transmigration  *migrant  *migratory  *emigrant  *immigrant'],
		['trans', 'across', ' *transfer  *translate  *transmit  *transfusion  *translucent  *transcend'],
		['gamy', 'marriage', ' *monogamy  *polygamy  *bigamy  *gamete  *autogamous  *exogamy']
];

var stemList_7 = [
		['numer', 'number', ' *enumerate  numeral  numerous  supernumeraries  numerology'],
		['fort', 'strong', ' *fortitude  fort  fortify  fortification  comfort  forte  fortissimo  pianoforte'],
		['osteo', 'bone', ' *osteopath  osteology  osteopathy  osteoblast  osteocyte  osteotomy'],
		['ornith', 'bird', ' *ornithology  ornithologist  ornithopter   ornithomancy'],
		['polis', 'city', '  *metropolis  megalopolis  police  polite  policy acropolis necropolis'],
		['fus', 'pour', ' *transfusion  infusion  infusion  fusillade  infuse  confusion'],
		['ego', 'I', ' *egomaniac egocentric  egotstical   egotist  egotize  egosim  alter ego'],
		['spir', 'breathe', ' *inspire  respiration  perspiration  expire  spirit  aspire  conspire'],
		['dia', 'across', ' *diagonal  diameter  dialouge  dialect  diatribe  diaphanous  dialectic'],
		['acr', 'sharp', ' *acrimonious  acerbity  acrid  acridine  acrimony  acerate'],
		['acro', 'high', ' *acrobat  acronym  acropolis  acrophobia  acromegaly  acrocarpous'],
		['culp', 'blame', ' *culprit  culpable  exculpate  inculpate  exculpatory'],
		['derm', 'skin', ' *dermatologist  dermatitis  pachyderm  hypodermic  ectoderm  endoderm'],
		['zo', 'animal', ' *zoo  protozoa  zoophilous  zooplankton  zoophagous  Mesozoic  zodiac'],
		['per', 'through', ' *perception  perforation  percolate  perambulate  peregrination'],
		['pac', 'peace', ' *pacify  pacfic  pacifist  pacifier  pacifism  Pax Romana  pacification'],
		['brev', 'short', ' *brevity  abbreviation  breve  breviary  brevirostrate  brief'],
		['necro', 'death', ' *necropolis  necromancer  necrophobia  necrotic  necrobiosis'],
		['urb', 'city', ' *urban  urbane  suburbs  urbanite  urbanologist  urbanism'],
		['pugn', 'fight', ' *pugnacious  reoungnant  pugilist  impugn  oppugn  inexpugnable'],
		['ecto', 'outer', ' *ectoderm  ectozoa  ectomorph  ectothermic  ectoplasm  ectoparasite'],
		['plasto', 'molded', ' *plastic  dermoplasty  rhinoplasty  plaster  plasticity  plastid'],
		['agog', 'leader', ' *dermagogue  pedagogue  synagogue  agogics  pedagogy  mystagogue'],
		['cle', 'small', ' *molecule  corpuscule  follicle  minuscule  ventricle  particle  vessicle'],
		['il', 'not', '  *illegal  illiterate  illict  illogical  illegible  illiberal']
];

var stemList_8 = [
		['sed', 'sit', ' *sedentary  sediment  sedan  sedative  sedate  supersede  assiduos  insidious'],
		['leg', 'read', ' *egible  legend  illegible  legendary  legibility  alleged'],
		['anim', 'mind', ' *equanimiy  animal  animated  animosity  magnanimous  animadversion'],
		['tort', 'twist', ' *contorted  torture  tortuous,  retort  distort  torturous  tort  tortilla'],
		['nym', 'name', ' *homonym  acronym  pseudonym  anonymous  patronymic  anomaly'],
		['sanct', 'holy', ' *sanctity  sanctimonious  sacrosanct  sanctuary  unsanctioned  sanctify'],
		['meta', 'change', ' *metamorphosis  metaphor  metaphysics  metastasize  metabolism'],
		['petr', 'rock', ' *peterify  petroleum  petrology  petroglyph  petrophilous  petrochemical'],
		['mir', 'wonder', ' *miracle  mirage  mirror  mirabile dictu  admire  mirabilia  miracle play'],
		['man', 'hand', ' *manual  manicure  manipulate  manacles  amanuensis  legerdemain'],
		['rect', 'right', ' *correct  rectitude  direct  rectilinear  rectangle  rectify  rector  erect'],
		['volv', 'roll', ' *revolve  onvolved  devolve  convoluted  volvox  revolution  volvulus'],
		['demi', 'half', ' *demigod  demitasse  demisemiquaver  demiurge  demimonde  demirep'],
		['retro', 'backward', ' *retroactive  retrofire  retrogress  retrospection  retrofit  retorse'],
		['sens', 'feel', ' *sense  sensitive  sensation  sensory  extrasensory  insensate'],
		['fy', 'make', ' *fortify  rectify  horrify  solidify  reify  transmorgrify  sanctify  pacify'],
		['ocul', 'eye', ' *binocular  monocular  ocular  oculist  oculomoter nerve  oculometer'],
		['cur', 'care for', ' *cure  curator  curative  cure-all  sinecure  secure  curate'],
		['ultra', 'beyond', ' *ltramarine  ultraconservative  ultraviolet  ultramundane'],
		['oid', 'appearance', ' *android (droid!)  anthropid  asteroid  adenoid  xyloid  haploid'],
		['gest', 'carry', ' *gestaion  digest  ingest  congestion  gesticulate  gesture'],
		['apt', 'fit', ' *adapt  aptitude  maladapted  adaptationaptly  aptness'],
		['tact', 'touch', ' *tactile  contact  tactics  tactcian  intact'],
		['voc', 'voice', ' *vociferously  vocal  sotto voce  invoaction  vocabulary  convocation'],
		['rid', 'laugh', ' *ridcule  deride  dersion  risibility  ridiculous']
];

var stemList_9 = [
		['path', 'feeling', ' *sympathy  pathetic  pathos  telepathy  empathy  apathy  idiopathy'],
		['a', 'not', ' *amoral  amorphous  atheist  apathy  agraphia  apolitical  aphasia  achromatic'],
		['nomy', 'law', ' *astronomy  economy  deuteronomy  taxonomy  heteronomy  nomothetic'],
		['fid', 'faith', ' *infidel  fidelity  confidence  diffident  bona fide  fiduciary  perfidy'],
		['caco', 'bad', ' *cacophony  cacography  cacodemon  cacoethes  cacodyl cacology'],
		['hetero', 'different', ' *heterodox  heteromorphic  heterogeneous  heterosexual  heteronym'],
		['sci', 'know', ' *science  conscience  prescience  omniscience  scientism  sciomancy'],
		['graph', 'write', ' *bibliography  photograph  autograph  polygraph  stenograph'],
		['lat', 'side', ' *bilateral  unilateral  lateral fin  multilateral  collateral  latitude  translate'],
		['lith', 'rock', ' *neolithic  paleolithic  lithograph  megalith  monolith  lithium  laccolith'],
		['tract', 'pull', ' *tractor  detract  retraction  attractive  protractor  contract  traction'],
		['in', 'in or not', ' *inscribe  insane  infidel  indefinite  incorrigible  insomnia'],
		['co', 'together', ' *cooperate  coordinating  coterminous  colloquy  coauthor  cotangent'],
		['phile', 'love', ' *philosopher  audiophile  bibliophile  philologist  philanthropy'],
		['ine', 'nature of', ' *porcine  crystalline  saturnine  canine  ursine  vulpine  bovine'],
		['ar', 'relating to', ' *pulsar  stellar  lunar  solar  secular  columnar  linear  circular'],
		['hexa', 'six', ' *hexagram  hexagon  hexapod  hexameter  hexahedron  hexarchy'],
		['fract', 'break', ' *fracture  infraction  fraction  refraction  refractory  fractious'],
		['platy', 'flat', ' *plateau  platyhelminthes  platypus  plate  platitude  platyrrhine'],
		['theo', 'god', ' *theology  pantheism  atheism  monotheism  apotheosis  henotheism'],
		['fin', 'end', ' *final  define  infinite  finial  finis  finisterre  infinitive  fin de siècle'],
		['hedron', 'sided object', ' *polyhedron  tetrahedron  heptahedron  octahedron  icosahedron'],
		['ambul', 'walk', ' *ambulatory  somnambulism  funambulist  ambulance  perambulate'],
		['ous', 'full of', ' *luminous  glorious  loquacious  vivacious  garrulous  anomalous  zealous'],
		['topo', 'place', ' *topographical  topology  topic  topiary  toponym  topognosia']
];

var stemList_10 = [
		['ped', 'foot or child', ' *orthopedist  pedagogue  centipede  expedition  pedestrian  pedestal'],
		['mort', 'death', ' *mortal  mortician  mortified  immortality  mortuary  moribund'],
		['carn', 'flesh', ' *carnivorous  incarnate  incarnated  carnival  carnation  carnage'],
		['psych', 'soul', ' *psychology  psychic  psychopathic  parapsychology  psychosis'],
		['ethno', 'race or culture', ' *ethnocentrism  ethnic group  ethnography  ethnologist'],
		['gen', 'origin', ' *genetics  hydrogen  progeny  engender  gene  ingenuous  indigenous'],
		['nat', 'born', ' *prenatal  native  natural  nativity  nation  nascent  natal  perinatal'],
		['paleo', 'old', ' *paleozoic  paleolithic  paleontologist  paleo anthropic  paleography'],
		['curs', 'run', ' *cursive  discursive  incursion  precursor  cursory  cursorial  cursor'],
		['crypt', 'hidden', ' *cryptic  cryptology  crypt  cryptogram  encrypt  cryptesthesia'],
		['cad', 'fall', ' *cascade  cadaver  cadence cadenza cadaverous  decadent'],
		['capit', 'head', ' *decapitate  capital  recapitulate  capitulation capitulum'],
		['loqu', 'talk', ' *loquacious circumlocution eloquent  soliloquy somniloquy  dialogue'],
		['sacro', 'holy', ' *sacrosanct  sacred  sacrifice  sacrament  sacrilege  consecrate'],
		['uni', 'one', ' *unicycle  universe  united  union  uniform  unison  unique  unicorn'],
		['ness', 'quality', ' *softness  redness  politeness  kindness  darkness  vagueness'],
		['alt', 'high', ' *altitude  alto  altimeter  altar  altocumulus  altiplano'],
		['ics', 'art', ' *politics  economics  aesthetics  graphics  ethics  calisthenics'],
		['iso', 'equal', ' *isothermal  isometric  isosceles  isomer  isocracy  isotope'],
		['vert', 'turn', ' *convert   revert  inverted  divert  vertex  controvert  extrovert  introvert'],
		['ate', 'cause', ' *domesticate implicate create procreate insinuate placate dominate'],
		['cor', 'heart', ' *core concord discord misericord cordial courageous'],
		['less', 'female', ' *lioness baroness seamstress governess'],
		['muta', 'change', ' *mutant mutation mutagenic mutable transmutation immutable'],
		['fug', 'flee', ' *centrifuge fugitive tempos fugue subterfuge refugee fugue']
];

var stemList_11 = [
		['i', 'plural', ' *vacilli  fungi  nuclei  alunmi  magi  octopi  gemini  homunculi  literati'],
		['jus', 'law', ' *justice  justify   unjust  [jus soli]  justiciary'],
		['lum', 'light', ' *luminary  luminous  illuminate  luminiferous  superluminous'],
		['ann', 'year', ' *annual superannuated  anniversary  annuity  perennial'],
		['apo', 'away or up', ' *apotheosis  apogee  apoplexy  apology  aphelion  apostasy'],
		['sen', 'old', ' *senile  senior  senator  seniority  senescent'],
		['sol', 'alone', ' *solitude  solitary  solo  soliloquy  desolate  solipsism  solifidian  consolidate'],
		['bas', 'low', ' *bass  base  basic  basal  bassoon  debase  contrabase  abase  bas-relief'],
		['rogat', 'ask', ' *interrogation  abrogate  derogatory  arrogare  supererogatory'],
		['parl', 'speak', ' *parliament  parley  parlor  parlance  parlando'],
		['potent', 'power', ' *potential  potentiometer  potentate  plenipotentiary  omnipotent'],
		['surg', 'rise', ' *resurgence  insurgence  surge  surgent'],
		['log', 'word or reason', ' *logic  neologism  philologist  logician  illogical  monologue'],
		['gram', 'writing', ' *telegram  pentagram  hexagram  hologram  grammar'],
		['cant', 'sing', ' *recant  cantata  incantation  descant  canticle  canto'],
		['reg', 'rule', ' *regal  regiment  regulate  regent  interregnum  regicide  regime'],
		['pro', 'forward', ' *provide  pronounce  program  prognosticate  prospect  prognosis  prolix  prolegomenon'],
		['gyn', 'woman', ' *androgynous  gynecologist  polygyny  misogynist  gynephobia'],
		['ag', 'to do', ' *agile  agent  agency  agitate  aggression  aggrade  agree'],
		['act', 'to do', ' *transact  react  action  activate  abreact  counteract  interact'],
		['mob', 'move', ' *mobility  mobile  immobile  mobilize  demobilize'],
		['sess', 'sit', ' *session  sessile  insessorial  sessility  obsessed'],
		['fic', 'make', ' *fortification  fiction  prolific  horrific  soporific'],
		['nounce', 'tell', ' *denounce  pronounce  announce  renounce  enunciate'],
		['andro', 'man', ' *androgynous  android(droid)  androgens  androphobia  polyandry']
];

var stemList_12 = [
		['an-', 'without', ' *anemia  anechoic  anaerobic  anorexia  anarchy'],
		['ab', 'away', ' *abnormal  abjure  absent  abroad  abrogate  abrupt  abduct  abdicate'],
		['mel', 'song', ' *melody  melodrama  melodion  melodious melodia'],
		['aden', 'gland', ' *adenoid  adenine  adenoma  adenovirus'],
		['aer', 'air', ' *aerobic  aerie  aerosol  aerial  aerobes  aerodynamics  malaria'],
		['alb', 'white', ' *albumen  alba  album  albino  albinism  albedo'],
		['ase', 'enzyme', ' *permease  galactosidase  protease  luciferase'],
		['epi', 'on', ' *epicenter  epidemic  epigram  epidermis  epigraph  epitaph'],
		['hum', 'earth', ' *humus  exhume  posthumous  humble  humiliate  human'],
	  ['-be', 'life', ' *microbe  aerobe  anaerobe'],
		['bon', 'good', ' *bonny bonanza (bon mot) bonus (bon vivant) bonhomie (bona fide)'],
		['struct', 'build', ' *construct destruct substructure instruction structure infrastructure'],
		['chlor', 'green', ' *chlorophyll chlorine chloroplasts chlorella'],
		['cyan', 'blue', ' *pyocyanin cyanide cyan cyanophyte cyanosis cyanotype'],
		['cyt', 'cell', ' *erythrocyte leucocyte cytology cytoplasm melanocyte'],
		['diplo', 'double', ' *diplococcus diploid diplomacy diplopoda diplopia'],
		['dys', 'bad', ' *dysentery dyslexia dystrophy dysfunction dysphonia'],
		['eco', 'house', ' *ecology economy ecosystem ecotone economist ecologist'],
		['emia', 'blood', ' *bacteremia anemia hypoglycemia toxemia'],
		['enter', 'intestine', ' *enteritis dysentery gastroenteritis enterozoan'],
		['erythro', 'red', ' *erythrocyte erythroblastosis erythrism erythromycin'],
		['idio', 'peculiar', ' *idiot idiosyncrasy idiomorphous idiom idiot savant'],
		['exo', 'out', ' *exotoxin exogenous exodus exorbitant exorcism exotic exobiology'],
		['im', 'not', ' *impossible impassable improbable imperfect immobile impecunious'],
		['fil', 'thread', ' *filiform filicineae filament filaria filigree defile']
	];

//put all stem lists in a variable
var allStemList = [stemList_1, stemList_2, stemList_3, stemList_4, stemList_5, stemList_6,
	  stemList_7, stemList_8, stemList_9, stemList_10 , stemList_11, stemList_12];
